name: Update Dependencies

on:
  schedule:
    - cron: '0 0 * * 1'  # Run once per week at midnight on Monday
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install pip-tools
      run: |
        python -m pip install --upgrade pip
        pip install pip-tools
    
    - name: Create branch for updates
      id: create_branch
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        DATE=$(date '+%Y%m%d')
        BRANCH_NAME="dependency-updates-${DATE}"
        git checkout -b $BRANCH_NAME
        echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
    
    - name: Update dependencies
      run: |
        if [ -f requirements.in ]; then
          pip-compile --upgrade requirements.in
          git add requirements.txt
        fi
        if ls requirements-*.in 1> /dev/null 2>&1; then
          for req_in in requirements-*.in; do
            pip-compile --upgrade $req_in
            git add ${req_in%.in}.txt
          done
        fi
    
    - name: Check for changes
      id: check_changes
      run: |
        if [ -z "$(git status --porcelain)" ]; then
          echo "No changes detected"
          echo "has_changes=false" >> $GITHUB_OUTPUT
        else
          echo "Changes detected"
          echo "has_changes=true" >> $GITHUB_OUTPUT
        fi
    
    - name: Commit and push changes
      if: steps.check_changes.outputs.has_changes == 'true'
      run: |
        git commit -m "Update dependencies"
        git push --set-upstream origin ${{ steps.create_branch.outputs.branch_name }}
    
    - name: Create Pull Request
      if: steps.check_changes.outputs.has_changes == 'true'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: "Auto-update dependencies"
        body: "This PR updates project dependencies to their latest versions. Please review the changes and run tests before merging."
        branch: ${{ steps.create_branch.outputs.branch_name }}
        base: development
        labels: dependencies
